### PR TITLE
Added simple smoke test for CI

### PR DESCRIPTION
**Pull request by aakarshg**
This addresses #5

### CODE REVIEW

**Comment by aakarshg** [comment]
rerun smoke

**Comment by aakarshg** [comment]
rerun smoke

**Comment by aakarshg** [comment]
#bingo :-)

**Comment by aakarshg** [comment]
@jtaleric for now we can use uperf because it seems to be the most stable workload we've.

**Comment by jtaleric** [comment]
@aakarshg ack.

**Pull request merged**
